name: build-deploy
on: 
    pull_request:
        types:
            - opened
            - synchronize

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Building the application..."

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying the application..."




#   deploy-job:
#     runs-on: ubuntu-latest
#     needs: build-job
#     steps:
#       - name: Deploy Step
#         run: echo "Deploying the application..."