name: If-demo
on: 
    push:
        branches:
            - main
            - dev
            - feature/*
            - prod
            - deploy
            
jobs:
    if-demo-job-name:
        runs-on: ubuntu-latest
        steps:
            - name: Run this Step
              if: github.ref_name== 'main'
              run: echo "This is main branch"
            - name: Run this Step
              if: github.ref_name == 'dev'
              run: echo "This is dev branch"
            - name: Run this Step
              if: github.ref_name == 'feature/test-feature'
              run: echo "This is test-feature branch"
    