name: or-condition-demo
on: 
    push:
        branches:
            - main
            - dev
            - feature/*
            - prod
            - deploy
            
jobs:
    if-demo-job-name:
        runs-on: ubuntu-latest
        steps:
            - name: Run this Step for first_name Abhishek or middle_name Mani
              if: github.actor== 'Abhishek' || github.actor== 'Mani'
              run: echo "This is main branch" ${{ github.ref_name }} 
    